version: "3.8"

services:
    dddjango:
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
                PYTHONBREAKPOINT: import ipdb;ipdb.set_trace
        volumes:
            - .:/src
